### ISSUE TITLE
Version display

### ISSUE THREAD

**Issue by sol-oriens** [sol-oriens/SR2-Community-Patch#1]
Although the Community Patch should be as non-intrusive as possible, I think it's a good thing to add a minor override to let users know that it is applied and which version. I repurposed the SoI / RS version display code for this. The result can be seen in the VersionCheck branch.
<br /><br />
This also means that modders (and us) overriding menus.as will need to include this in their logic. I already did it for SoI to nicely display the SoI, RS and Community Patch versions on top of each other on the title screen and it's both easy to do and good-looking.
<br /><br />
Thoughts?

**Comment by DaloLorn** [comment]
My first thought is "do we really need all these branches?". :P 

That being said, I tend to agree. Generally speaking, I believe that the only place where non-intrusiveness trumps functionality should be gameplay - fix bugs, make QoL changes to the UI, etc., but make the game play roughly the way it used to.

**Comment by sol-oriens** [comment]
The purpose of the branches is to more easily track the origin of the different things that will be added to the version. Makes it easier to maintain a checklist rather than painfully delve into one giant list of commits.
The other purpose is to easily be able to scrap 'maybe' stuff from that version should it be decided so, like this very point about displaying the CP version, for instance.

**Comment by sol-oriens** [comment]
As of v1.0.0 this has been implemented as an optional feature.
